# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  fast_finish: true

install:
  - pip install "Django>=1.11.19,<2.2" # from test_requirements.txt
  - pip install -r ci_requirements.txt
  - pip install tox-travis

script:
  - coverage erase
  - tox

after_success:
  - coverage combine --append
  - coverage report -m
  - pip install codecov
  - codecov
